FROM archlinux:latest

COPY ./docker/mirrorlist /etc/pacman.d/mirrorlist


RUN pacman-db-upgrade

RUN pacman -Syyu --noconfirm npm nodejs


COPY ./test/package.json /test/package.json
RUN npm install --prefix /test


COPY ./install /test/install
COPY ./compose /test/compose
COPY ./test /test
WORKDIR /test


ARG values_script
RUN /bin/bash install/install.sh "${values_script}"

CMD [ "sh", "-c", "sleep 3 && npm test" ]
