services:
  reverseproxy:
    image: my_nginx:0.0.0
    build:
      context: ..
      dockerfile: compose/Dockerfile.nginx
    container_name: my_nginx
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    links:
      - "kart_api:karting"
  
  kart_api:
    image: kartapi:0.0.0
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        values_script : compose/values.api.sh
    container_name: kartapi
    ports:
      - "6029:6029"
